version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-product-explorer
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_SERVER_URL=https://world.openfoodfacts.org
    restart: unless-stopped
